#!/usr/bin/env bash
#
# Generated by PolyRig. Review init.plan.md before running.
# This script only creates context files and safe directories, and initializes
# a git repository when the target is not already inside one.
#
# It must NEVER: install packages, edit build files, fetch anything remote,
# generate business code, or make commits. Those remain manual follow-ups in
# init.plan.md.
#
# polyrig: fill the {{PLACEHOLDER}} values below and keep every added line
# polyrig: within the safe operations allowed here (mkdir -p, touch, echo,
# polyrig: and the guarded git init below).
# polyrig: strip the `polyrig:` marker comments from the final artifact.

set -euo pipefail

# Version control — the context layer must travel with the repo.
# Skipped when the target already lives inside a git work tree.
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  git init -b main
fi
if [ ! -f .gitignore ]; then
  echo ".env" > .gitignore
fi

# Context directories
mkdir -p docs/stacks
mkdir -p docs/domains
mkdir -p .polyrig

# polyrig: one line per selected pack, replacing the two examples below.
mkdir -p "docs/stacks/{{STACK_SHORT_NAME}}"
mkdir -p "docs/domains/{{DOMAIN_SHORT_NAME}}"

# Environment variable placeholder (never commit the real .env)
touch .env.example

# polyrig: additional SAFE lines only (mkdir -p / touch for context files).
# polyrig: {{ADDITIONAL_SAFE_INIT_LINES}}

echo "PolyRig init complete for {{PROJECT_NAME}}."
echo "Created: git repo (if absent), .gitignore, docs/stacks/, docs/domains/, .polyrig/, .env.example."
echo "Next: work through the manual follow-ups in init.plan.md (including the first commit), then read AGENTS.md before starting any feature."
